trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: TerraformPlan
  displayName: "Terraform Plan Stage"
  jobs:
    - job: Plan
      steps:
        - checkout: self
        - task: TerraformInstaller@0
          displayName: "Install Terraform"
          inputs:
            terraformVersion: "1.5.7"
        - script: |
            terraform init
            terraform plan -out=tfplan
          displayName: "Run Terraform Plan"
        - task: PublishBuildArtifacts@1
          displayName: "Publish Terraform Plan Artifact"
          inputs:
            PathtoPublish: "$(Build.SourcesDirectory)/tfplan"
            artifactName: "tfplan"
            publishLocation: Container

- stage: ManualApproval
  displayName: "Manual Approval Stage"
  jobs:
    - job: WaitApproval
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: ManualValidation@0
          displayName: "Pause for Manual Approval"
          inputs:
            notifyUsers: "approver@example.com"
            instructions: "Review the Terraform plan artifact before applying. Approve if it meets your requirements."
            timeoutInMinutes: 60
            onTimeout: reject

- stage: TerraformApply
  displayName: "Terraform Apply Stage"
  dependsOn: ManualApproval
  jobs:
    - job: Apply
      steps:
        - checkout: self
        - task: TerraformInstaller@0
          displayName: "Install Terraform"
          inputs:
            terraformVersion: "1.5.7"
        - task: DownloadBuildArtifacts@0
          displayName: "Download Terraform Plan Artifact"
          inputs:
            buildType: specific
            artifactName: "tfplan"
            downloadPath: "$(Pipeline.Workspace)"
        - script: |
            terraform init
            terraform apply "$(Pipeline.Workspace)/tfplan/tfplan"
          displayName: "Run Terraform Apply"
